name: Test

on: 
  push:
    branches-ignore:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gcc-arm-none-eabi-10.3
      run: |
        wget -q "https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2"
        sudo tar -xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2 -C /usr/
        export PATH=/usr/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH
    - name: Install packages build sbtools required
      run: |
        sudo apt-get update
        sudo apt-get install libcrypto++-dev libusb-1.0-0-dev -y
    - name: Build sbtools
      run: |
        export PATH=/usr/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH
        cd tools/sbtools
        make
        cd ../sys_signer
        cmake .
        cmake --build .
        cp sysigner ../
        cd ../..
        cd Libs/src/micropython-master/ports/eoslib
        make
        cd ../../../../..
    - name: CMake configure
      run: |
        export PATH=/usr/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH
        cmake .
    - name : CMake build
      run: |
        export PATH=/usr/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH
        cmake --build .
